//! Configuration center (INFRA-01 / INFRA-04, D-10/D-12/D-13).

use std::io::Write;
use std::path::PathBuf;

use crate::error::{MyboxError, Result};
use crate::module::Module;

/// Section-based TOML configuration center, namespaced per module id.
///
/// - **INFRA-01:** each module's config lives under `[module_id]`; framework
///   hotkeys under a framework-owned `[hotkeys]` section.
/// - **D-10:** the whole file is cached in memory on load; `get`/`set` hit
///   memory and [`save`](Self::save) writes the full table back.
/// - **D-12/D-13:** on first run the file is generated by merging every
///   registered module's `default_config()`, so users get a complete commented
///   config on first launch.
#[derive(Debug)]
pub struct ConfigCenter {
    /// Absolute path of the config file (INFRA-04).
    path: PathBuf,
    /// In-memory cache of the whole TOML document (D-10).
    table: parking_lot::RwLock<toml::Table>,
}

impl Default for ConfigCenter {
    fn default() -> Self {
        Self {
            path: PathBuf::new(),
            table: parking_lot::RwLock::new(toml::Table::new()),
        }
    }
}

impl ConfigCenter {
    /// Load the config, generating the file on first run (D-12/D-13).
    ///
    /// The file lives at `config_file_path()` (INFRA-04). When it does not
    /// exist, a commented `config.toml` is generated from every module's
    /// `default_config()` plus the framework `[hotkeys]` defaults, then loaded.
    /// When it exists it is parsed directly; a malformed file yields
    /// `MyboxError::ConfigParse` rather than panicking (T-1-01).
    pub fn load_or_create(modules: &[&dyn Module]) -> Result<Self> {
        let path = config_file_path().map_err(|e| MyboxError::Io(std::io::Error::other(e)))?;
        Self::load_or_create_at(path, modules)
    }

    /// Same as [`load_or_create`](Self::load_or_create) but against an explicit
    /// path. `load_or_create` always uses the platform path; tests pass a temp
    /// directory here so the real user config dir is never touched.
    fn load_or_create_at(path: PathBuf, modules: &[&dyn Module]) -> Result<Self> {
        if !path.exists() {
            Self::generate_file(&path, modules)?;
        }
        let content = std::fs::read_to_string(&path)?;
        // `toml::Table: FromStr<Err = toml::de::Error>`; the From bridge in
        // error.rs maps that to MyboxError::ConfigParse (T-1-01: no panic).
        let table: toml::Table = content.parse()?;
        Ok(Self {
            path,
            table: parking_lot::RwLock::new(table),
        })
    }

    /// First-run generation (D-12/D-13): write a commented `config.toml` made of
    /// one section per module (`default_config()`) plus the framework
    /// `[hotkeys]` section (RESEARCH §10.4).
    fn generate_file(path: &PathBuf, modules: &[&dyn Module]) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let mut table = toml::Table::new();
        for module in modules {
            let id = module.id();
            let defaults = module.default_config();
            table.insert(id.to_string(), toml::Value::Table(defaults));
        }
        let mut hotkeys = toml::Table::new();
        hotkeys.insert(
            "open_test_window".to_string(),
            toml::Value::String("Cmd+Shift+T".to_string()),
        );
        hotkeys.insert(
            "exit".to_string(),
            toml::Value::String("Cmd+Shift+Q".to_string()),
        );
        table.insert("hotkeys".to_string(), toml::Value::Table(hotkeys));

        let mut file = std::fs::File::create(path)?;
        writeln!(file, "# mybox configuration")?;
        writeln!(
            file,
            "# Generated on first run from every module's default_config()."
        )?;
        writeln!(file, "# Edit values here and restart the app to apply.\n")?;
        let serialized = toml::to_string_pretty(&table)?;
        write!(file, "{serialized}")?;
        Ok(())
    }

    /// Read a single key from a module's section (D-10: served from memory).
    pub fn get(&self, module: &str, key: &str) -> Option<toml::Value> {
        let table = self.table.read();
        table.get(module)?.as_table()?.get(key).cloned()
    }

    /// Read an entire module section as an owned table, if it exists.
    pub fn get_section(&self, module: &str) -> Option<toml::Table> {
        let table = self.table.read();
        table.get(module)?.as_table().cloned()
    }

    /// Write a key into a module's section (D-10: memory only; persist with
    /// [`save`](Self::save)). Creates the section if it does not exist.
    pub fn set(&self, module: &str, key: &str, value: toml::Value) {
        let mut table = self.table.write();
        let section = table
            .entry(module)
            .or_insert_with(|| toml::Value::Table(toml::Table::new()));
        if let Some(section) = section.as_table_mut() {
            section.insert(key.to_string(), value);
        }
    }

    /// Persist the whole in-memory table back to the file (D-10 full write-back).
    pub fn save(&self) -> Result<()> {
        let serialized = toml::to_string_pretty(&*self.table.read())?;
        std::fs::write(&self.path, serialized)?;
        Ok(())
    }

    /// Parse the `[hotkeys].<action>` string into a [`HotKey`] (D-11).
    ///
    /// Returns `Ok(None)` when the action is not configured; a configured but
    /// invalid string yields `MyboxError::HotkeyParse` (T-1-01, never panic).
    pub fn hotkey(&self, action: &str) -> Result<Option<global_hotkey::hotkey::HotKey>> {
        let table = self.table.read();
        let Some(raw) = table
            .get("hotkeys")
            .and_then(|s| s.as_table())
            .and_then(|s| s.get(action))
            .and_then(|v| v.as_str())
        else {
            return Ok(None);
        };
        let hk = raw.parse().map_err(|e| {
            MyboxError::HotkeyParse(format!("invalid hotkey for '{action}' ('{raw}'): {e}"))
        })?;
        Ok(Some(hk))
    }
}

/// Platform user-config directory for mybox, resolved via
/// `directories::ProjectDirs::from("", "", "mybox")` (INFRA-04):
/// macOS `~/Library/Application Support/mybox/`.
///
/// Returns `Err` (never panics) when the platform has no config directory.
pub fn config_dir() -> anyhow::Result<PathBuf> {
    directories::ProjectDirs::from("", "", "mybox")
        .map(|dirs| dirs.config_dir().to_path_buf())
        .ok_or_else(|| anyhow::anyhow!("could not resolve the platform config directory"))
}

/// Full path to the config file: `config_dir()/config.toml` (INFRA-04 contract).
pub fn config_file_path() -> anyhow::Result<PathBuf> {
    Ok(config_dir()?.join("config.toml"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::context::ModuleContext;
    use crate::module::Module;
    use std::sync::atomic::{AtomicUsize, Ordering};

    /// A fake module whose `default_config()` carries a known value (D-13
    /// contract fixture for the first-run generation test).
    struct FakeModule {
        id: &'static str,
    }

    impl FakeModule {
        fn new(id: &'static str) -> Self {
            Self { id }
        }
    }

    impl Module for FakeModule {
        fn id(&self) -> &'static str {
            self.id
        }
        fn name(&self) -> &str {
            self.id
        }
        fn init(&self, _ctx: &ModuleContext) -> anyhow::Result<()> {
            Ok(())
        }
        fn default_config(&self) -> toml::Table {
            let mut t = toml::Table::new();
            t.insert(
                "message".to_string(),
                toml::Value::String("hello from test".to_string()),
            );
            t
        }
    }

    // INFRA-04 path contract (from 01-01-05): the platform config dir is
    // resolved via directories and the file is <dir>/config.toml.
    #[test]
    fn config_dir_resolves_to_mybox_dir() {
        let dir = config_dir().expect("config dir must resolve");
        assert_eq!(
            dir.file_name().and_then(|n| n.to_str()),
            Some("mybox"),
            "config dir basename should be 'mybox', got {:?}",
            dir
        );
    }

    #[test]
    fn config_file_path_contract() {
        let p = config_file_path().expect("config file path must resolve");
        assert_eq!(p.file_name().and_then(|n| n.to_str()), Some("config.toml"));
        assert_eq!(
            p.parent().and_then(|d| d.file_name()).and_then(|n| n.to_str()),
            Some("mybox")
        );
        // macOS-specific tail, verified only when running on macOS.
        #[cfg(target_os = "macos")]
        {
            let s = p.to_string_lossy();
            assert!(
                s.contains("Library/Application Support/mybox/config.toml"),
                "unexpected macOS config path: {s}"
            );
        }
    }

    /// Monotonic counter so each test gets a unique temp path; tests never touch
    /// the real user config dir.
    static COUNTER: AtomicUsize = AtomicUsize::new(0);

    fn temp_config_path() -> PathBuf {
        let n = COUNTER.fetch_add(1, Ordering::SeqCst);
        std::env::temp_dir().join(format!("mybox-config-test-{}-{n}", std::process::id()))
    }

    #[test]
    fn first_run_generates_module_and_hotkeys_sections() {
        let path = temp_config_path();
        let fake = FakeModule::new("test");
        let modules: Vec<&dyn Module> = vec![&fake];
        let cc = ConfigCenter::load_or_create_at(path.clone(), &modules).expect("load_or_create");

        // The generated file has a [test] section with the module default and a
        // [hotkeys] section with the framework defaults (D-12/D-13, RESEARCH §10.4).
        let content = std::fs::read_to_string(&path).expect("file written");
        assert!(content.contains("[test]"), "missing [test] section: {content}");
        assert!(content.contains("hello from test"), "missing module default: {content}");
        assert!(content.contains("[hotkeys]"), "missing [hotkeys] section: {content}");
        assert!(
            content.contains("open_test_window"),
            "missing framework hotkey default: {content}"
        );

        // In-memory view matches.
        assert_eq!(
            cc.get("test", "message"),
            Some(toml::Value::String("hello from test".to_string()))
        );
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn namespace_isolation_between_modules() {
        let path = temp_config_path();
        let a = FakeModule::new("a");
        let b = FakeModule::new("b");
        let modules: Vec<&dyn Module> = vec![&a, &b];
        let cc = ConfigCenter::load_or_create_at(path.clone(), &modules).expect("load_or_create");

        cc.set("a", "x", toml::Value::Integer(1));
        cc.set("b", "y", toml::Value::Integer(2));

        assert_eq!(cc.get("a", "x"), Some(toml::Value::Integer(1)));
        assert_eq!(cc.get("b", "y"), Some(toml::Value::Integer(2)));
        assert_eq!(cc.get("a", "y"), None, "module A must not see B's keys");
        assert_eq!(cc.get("b", "x"), None, "module B must not see A's keys");
        assert!(
            !cc.get_section("a").expect("section a").contains_key("y"),
            "section [a] must not contain module B's keys"
        );
        assert!(
            !cc.get_section("b").expect("section b").contains_key("x"),
            "section [b] must not contain module A's keys"
        );
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn set_save_reload_round_trips() {
        let path = temp_config_path();
        let fake = FakeModule::new("test");
        let modules: Vec<&dyn Module> = vec![&fake];
        let cc = ConfigCenter::load_or_create_at(path.clone(), &modules).expect("first load");
        cc.set("test", "count", toml::Value::Integer(3));
        cc.save().expect("full write-back");

        let reloaded = ConfigCenter::load_or_create_at(path.clone(), &modules).expect("reload");
        assert_eq!(
            reloaded.get("test", "count"),
            Some(toml::Value::Integer(3)),
            "saved value must survive a reload (D-10 full write-back)"
        );
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn malformed_file_returns_config_parse_error_not_panic() {
        let path = temp_config_path();
        std::fs::write(&path, "key = = broken").expect("write invalid toml");
        let err = ConfigCenter::load_or_create_at(path.clone(), &[]).unwrap_err();
        assert!(matches!(err, MyboxError::ConfigParse(_)), "got {err:?}");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn hotkey_accessor_parses_config_string() {
        let path = temp_config_path();
        let fake = FakeModule::new("test");
        let modules: Vec<&dyn Module> = vec![&fake];
        let cc = ConfigCenter::load_or_create_at(path.clone(), &modules).expect("load_or_create");

        // First-run defaults put "Cmd+Shift+T" under [hotkeys].open_test_window.
        let hk = cc.hotkey("open_test_window").expect("valid config");
        assert!(hk.is_some(), "open_test_window hotkey should exist after first run");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn hotkey_accessor_rejects_invalid_string() {
        let path = temp_config_path();
        std::fs::write(
            &path,
            "[hotkeys]\nopen_test_window = \"not-a-hotkey!!\"\n",
        )
        .expect("write config");
        let cc = ConfigCenter::load_or_create_at(path.clone(), &[]).expect("load");
        let err = cc.hotkey("open_test_window").unwrap_err();
        assert!(matches!(err, MyboxError::HotkeyParse(_)), "got {err:?}");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn hotkey_accessor_returns_none_for_unconfigured_action() {
        let path = temp_config_path();
        let fake = FakeModule::new("test");
        let modules: Vec<&dyn Module> = vec![&fake];
        let cc = ConfigCenter::load_or_create_at(path.clone(), &modules).expect("load_or_create");
        assert!(cc.hotkey("does_not_exist").expect("no error").is_none());
        let _ = std::fs::remove_file(&path);
    }
}
